permalink: /:year/:month/:day/:title.html
# paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: leopardpan
  email: baixin.pan@tendcloud.com
  link: voyagelab.github.io
  weibo: 
  github: https://github.com/leopardpan
  music: 
  linkedin: 

# 站点信息
title: leopard
description: My team blog
url: voyagelab.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: 

# 主题设置，自动激活某个标签
active: iOS

# 首页除了最新文章外显示分类
cates: 
  - iOS
  - Android

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档